package jarrid.keyper.cli

import kotlinx.coroutines.runBlocking


class Deploy :
    BaseSubcommand(help = "Deploy module implements Terraform Cloud Development Kit underneath. It scans existing key configs generated by key module and programatically construct terraform provider, modules and resources accordingly. For more information, visit: https://jarrid.xyz") {
    override fun run() = runBlocking {
        runAsync()
    }

    private suspend fun runAsync() {

        runTf()

    }
}