name: Test Keyper Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-keyper-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Keyper Action (Deploy Plan)
        id: keyper
        uses: ./
        with:
          args: "deploy plan"
